"""
Generate training loss plots from pre-loaded data.
Requires: training_data_all.csv (generated by load_and_prepare_data.py)
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

class TrainingLossPlotter:
    def __init__(self, data_dir, output_dir):
        self.data_dir = Path(data_dir)
        self.output_dir = Path(output_dir)
        self.fig_dir = self.output_dir / 'figures'
        self.fig_dir.mkdir(parents=True, exist_ok=True)
    
    def load_training_data(self):
        """Load pre-processed aggregated training data."""
        csv_path = self.data_dir / 'training_data_aggregated.csv'
        if not csv_path.exists():
            raise FileNotFoundError(f"Training data not found at {csv_path}. Run load_and_prepare_data.py first.")
        
        print(f"Loading training data from {csv_path}...")
        df = pd.read_csv(csv_path)
        print(f"  Loaded {len(df)} aggregated training records")
        return df
    
    def plot_training_loss_by_opponent(self, df):
        """Plot training loss by game over epochs."""
        print("\nGenerating training loss plot...")
        
        game_map = {
            'Prisoners-Dilemma': 'prisoners-dilemma',
            'Stag-Hunt': 'stag-hunt',
            'Hawk-Dove': 'hawk-dove',
        }
        
        if 'total_loss_mean' not in df.columns or 'game_name' not in df.columns:
            print("  Required columns not found, skipping...")
            return
        
        # Group by game and epoch to compute overall statistics
        records = []
        for idx, row in df.iterrows():
            game = game_map.get(row['game_name'], None)
            if game is None:
                continue
            
            records.append({
                'Game': game.replace('-', ' ').title(),
                'Epoch': row['epoch'],
                'Loss': row['total_loss_mean']
            })
        
        df_loss = pd.DataFrame.from_records(records)
        
        if df_loss.empty:
            print("  No valid loss data found!")
            return
        
        # Create line plot by game
        fig, ax = plt.subplots(figsize=(10, 6))
        
        for game in df_loss['Game'].unique():
            game_data = df_loss[df_loss['Game'] == game]
            epoch_stats = game_data.groupby('Epoch')['Loss'].agg(['mean', 'std']).reset_index()
            
            ax.plot(epoch_stats['Epoch'], epoch_stats['mean'], linewidth=2, label=game)
            ax.fill_between(epoch_stats['Epoch'],
                           epoch_stats['mean'] - epoch_stats['std'],
                           epoch_stats['mean'] + epoch_stats['std'],
                           alpha=0.2)
        
        ax.set_xlabel('Epoch', fontsize=12)
        ax.set_ylabel('Training Loss', fontsize=12)
        ax.set_title('Training Loss by Game', fontsize=14, fontweight='bold')
        ax.legend(fontsize=11)
        ax.grid(alpha=0.3)
        ax.set_ylim(bottom=0)
        
        fig.tight_layout()
        
        # Save
        fname = self.fig_dir / 'training_loss_by_game.png'
        fig.savefig(fname, dpi=150)
        plt.close(fig)
        
        print(f"  Saved to {fname}")
    
    def plot_cooperation_probability_by_game(self, df):
        """Plot mean cooperation probability trajectory for each game with cleaner styling."""
        print("\nGenerating cooperation probability by game plot...")
        
        game_map = {
            'Prisoners-Dilemma': 'prisoners-dilemma',
            'Stag-Hunt': 'stag-hunt',
            'Hawk-Dove': 'hawk-dove',
        }
        
        if 'policy_prob_cooperate_mean' not in df.columns or 'game_name' not in df.columns:
            print("  Required columns not found, skipping...")
            return
        
        # Group by game and epoch to compute mean and std
        game_epoch_groups = []
        
        for game_name, game_key in game_map.items():
            game_df = df[df['game_name'] == game_name]
            if game_df.empty:
                continue
            
            # Group by epoch and compute statistics
            epoch_stats = game_df.groupby('epoch')['policy_prob_cooperate_mean'].agg(['mean', 'std']).reset_index()
            epoch_stats['game'] = game_key.replace('-', ' ').title()
            game_epoch_groups.append(epoch_stats)
        
        if not game_epoch_groups:
            print("  No cooperation probability data found!")
            return
        
        # Plot with cleaner style
        fig, ax = plt.subplots(figsize=(10, 6))
        
        colors = {'Prisoners Dilemma': '#1f77b4', 'Stag Hunt': '#ff7f0e', 'Hawk Dove': '#2ca02c'}
        
        for epoch_stats in game_epoch_groups:
            game = epoch_stats['game'].iloc[0]
            color = colors.get(game, None)
            
            # Plot mean line
            ax.plot(epoch_stats['epoch'], epoch_stats['mean'], 
                   linewidth=2, label=game, color=color)
            
            # Add shaded std region
            ax.fill_between(epoch_stats['epoch'],
                           epoch_stats['mean'] - epoch_stats['std'],
                           epoch_stats['mean'] + epoch_stats['std'],
                           alpha=0.2, color=color)
        
        ax.set_title('Mean Cooperation Probability by Game', fontsize=14, fontweight='bold')
        ax.set_xlabel('Episode', fontsize=12)
        ax.set_ylabel('Cooperation Probability', fontsize=12)
        ax.set_ylim(0, 1)
        ax.legend(fontsize=11)
        ax.grid(alpha=0.3)
        
        fig.tight_layout()
        
        # Save
        fname = self.fig_dir / 'cooperation_probability_by_game.png'
        fig.savefig(fname, dpi=150)
        plt.close(fig)
        
        print(f"  Saved to {fname}")
    
    def run(self):
        """Generate all training-related plots."""
        print("="*60)
        print("TRAINING LOSS PLOTTER")
        print("="*60)
        
        df = self.load_training_data()
        
        self.plot_training_loss_by_opponent(df)
        self.plot_cooperation_probability_by_game(df)
        
        print("\n" + "="*60)
        print("TRAINING PLOTS COMPLETE")
        print("="*60)
        print(f"Figures saved to: {self.fig_dir}")


if __name__ == '__main__':
    plotter = TrainingLossPlotter(
        data_dir='experiments/analysis_scripts/output/whole_population_generalization/data',
        output_dir='experiments/analysis_scripts/output/whole_population_generalization'
    )
    plotter.run()
