"""
Generate generalization heatmaps from pre-loaded data.
Requires: game_agent_averaged.csv (generated by load_and_prepare_data.py)
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

class GeneralizationHeatmapPlotter:
    def __init__(self, data_dir, output_dir):
        self.data_dir = Path(data_dir)
        self.output_dir = Path(output_dir)
        self.fig_dir = self.output_dir / 'figures'
        self.fig_dir.mkdir(parents=True, exist_ok=True)
    
    def load_game_agent_data(self):
        """Load pre-processed game-agent averaged data."""
        csv_path = self.data_dir / 'game_agent_averaged.csv'
        if not csv_path.exists():
            raise FileNotFoundError(f"Game-agent data not found at {csv_path}. Run load_and_prepare_data.py first.")
        
        print(f"Loading game-agent averaged data from {csv_path}...")
        df = pd.read_csv(csv_path)
        print(f"  Loaded {len(df)} aggregated records")
        
        # Print summary
        for train_game in sorted(df['train_game'].unique()):
            subset = df[df['train_game'] == train_game]
            print(f"  {train_game}: {len(subset)} test conditions, {subset['n_seeds'].iloc[0]} seeds")
        
        return df
    
    def plot_game_agent_heatmaps(self, df):
        """
        Generate one heatmap per trained game-agent.
        Each heatmap: 3 test games (rows) × 5 opponents (columns)
        """
        print("\nGenerating individual game-agent heatmaps...")
        
        game_order = ['prisoners-dilemma', 'stag-hunt', 'hawk-dove']
        opponent_order = [0.1, 0.3, 0.5, 0.7, 0.9]
        
        for train_game in sorted(df['train_game'].unique()):
            agent_data = df[df['train_game'] == train_game]
            
            # Create pivot table
            pivot = agent_data.pivot_table(
                index='test_game',
                columns='opponent_prob',
                values='mean_normalized_reward',
                aggfunc='mean'
            )
            
            # Reindex to ensure consistent ordering
            pivot = pivot.reindex(index=game_order, columns=opponent_order)
            
            # Create heatmap
            fig, ax = plt.subplots(figsize=(10, 6))
            sns.heatmap(
                pivot,
                annot=True,
                fmt='.3f',
                cmap='RdYlGn',
                vmin=0,
                vmax=1,
                cbar_kws={'label': 'Mean Normalized Reward'},
                ax=ax,
                linewidths=0.5,
                center=0.5
            )
            
            # Format labels
            ax.set_ylabel('Test Game', fontsize=12)
            ax.set_xlabel('Opponent Defection Probability', fontsize=12)
            ax.set_yticklabels([g.replace('-', ' ').title() for g in game_order], rotation=0)
            ax.set_xticklabels(opponent_order, rotation=0)
            
            # Title
            train_game_title = train_game.replace('-', ' ').title()
            ax.set_title(f'Agent Trained on {train_game_title}\n(Mean across 5 seeds)', 
                        fontsize=14, fontweight='bold')
            
            fig.tight_layout()
            
            # Save
            fname = self.fig_dir / f'game_agent_heatmap_{train_game}.png'
            fig.savefig(fname, dpi=150, bbox_inches='tight')
            plt.close(fig)
            
            print(f"  Saved: {fname.name}")
    
    def plot_combined_heatmap(self, df):
        """
        Generate a single large heatmap showing all 3 game-agents side by side.
        Layout: 3 rows (test games) × 3 columns (train games)
        """
        print("\nGenerating combined heatmap for all game-agents...")
        
        game_order = ['prisoners-dilemma', 'stag-hunt', 'hawk-dove']
        opponent_order = [0.1, 0.3, 0.5, 0.7, 0.9]
        
        # Create figure with 3 subplots side by side
        fig, axes = plt.subplots(1, 3, figsize=(18, 6), sharey=True)
        
        for idx, train_game in enumerate(game_order):
            agent_data = df[df['train_game'] == train_game]
            
            # Create pivot table
            pivot = agent_data.pivot_table(
                index='test_game',
                columns='opponent_prob',
                values='mean_normalized_reward',
                aggfunc='mean'
            )
            
            # Reindex
            pivot = pivot.reindex(index=game_order, columns=opponent_order)
            
            # Create heatmap
            ax = axes[idx]
            sns.heatmap(
                pivot,
                annot=True,
                fmt='.3f',
                cmap='RdYlGn',
                vmin=0,
                vmax=1,
                cbar=True if idx == 2 else False,
                cbar_kws={'label': 'Mean Normalized Reward'} if idx == 2 else {},
                ax=ax,
                linewidths=0.5,
                center=0.5
            )
            
            # Format labels
            if idx == 0:
                ax.set_ylabel('Test Game', fontsize=12)
                ax.set_yticklabels([g.replace('-', ' ').title() for g in game_order], rotation=0)
            else:
                ax.set_ylabel('')
            
            ax.set_xlabel('Opponent Defect. Prob.', fontsize=12)
            ax.set_xticklabels(opponent_order, rotation=0)
            
            # Title
            train_game_title = train_game.replace('-', ' ').title()
            ax.set_title(f'Trained on\n{train_game_title}', fontsize=12, fontweight='bold')
        
        fig.suptitle('Generalization Performance: All Game-Agents (Mean across 5 seeds)', 
                    fontsize=16, fontweight='bold', y=1.02)
        fig.tight_layout()
        
        # Save
        fname = self.fig_dir / 'all_game_agents_combined_heatmap.png'
        fig.savefig(fname, dpi=150, bbox_inches='tight')
        plt.close(fig)
        
        print(f"  Saved: {fname.name}")
    
    def plot_within_vs_between_task(self, df):
        """
        Create a summary plot showing within-task vs between-task performance.
        """
        print("\nGenerating within-task vs between-task comparison...")
        
        # Create a copy with task match indicator
        df_copy = df.copy()
        df_copy['task_match'] = df_copy['train_game'] == df_copy['test_game']
        
        # Aggregate by task_match and opponent
        summary = df_copy.groupby(['task_match', 'opponent_prob']).agg({
            'mean_normalized_reward': ['mean', 'std']
        }).reset_index()
        
        summary.columns = ['task_match', 'opponent_prob', 'mean_reward', 'std_reward']
        summary['condition'] = summary['task_match'].map({True: 'Within-Task', False: 'Between-Task'})
        
        # Plot
        fig, ax = plt.subplots(figsize=(10, 6))
        
        for condition in ['Within-Task', 'Between-Task']:
            subset = summary[summary['condition'] == condition]
            ax.plot(subset['opponent_prob'], subset['mean_reward'], 
                   marker='o', linewidth=2, label=condition)
            ax.fill_between(subset['opponent_prob'],
                           subset['mean_reward'] - subset['std_reward'],
                           subset['mean_reward'] + subset['std_reward'],
                           alpha=0.2)
        
        ax.set_xlabel('Opponent Defection Probability', fontsize=12)
        ax.set_ylabel('Mean Normalized Reward', fontsize=12)
        ax.set_title('Within-Task vs Between-Task Generalization', fontsize=14, fontweight='bold')
        ax.legend(fontsize=11)
        ax.grid(alpha=0.3)
        ax.set_ylim(0, 1)
        
        fig.tight_layout()
        
        # Save
        fname = self.fig_dir / 'within_vs_between_task.png'
        fig.savefig(fname, dpi=150, bbox_inches='tight')
        plt.close(fig)
        
        print(f"  Saved: {fname.name}")
    
    def run(self):
        """Generate all generalization heatmaps."""
        print("="*60)
        print("GENERALIZATION HEATMAP PLOTTER")
        print("="*60)
        
        df = self.load_game_agent_data()
        
        self.plot_game_agent_heatmaps(df)
        self.plot_combined_heatmap(df)
        self.plot_within_vs_between_task(df)
        
        print("\n" + "="*60)
        print("GENERALIZATION PLOTS COMPLETE")
        print("="*60)
        print(f"Figures saved to: {self.fig_dir}")


if __name__ == '__main__':
    plotter = GeneralizationHeatmapPlotter(
        data_dir='experiments/analysis_scripts/output/whole_population_generalization/data',
        output_dir='experiments/analysis_scripts/output/whole_population_generalization'
    )
    plotter.run()
