#!/usr/bin/env python3
"""
CORRECTED explanation: What actually happens at test time.

The network does NOT receive rewards or learn during testing.
So why do we observe different behaviors across opponents?
"""

print("=" * 80)
print("CORRECTED: WHAT ACTUALLY HAPPENS AT TEST TIME")
print("=" * 80)
print()

print("FACT 1: Network Inputs (Test Time)")
print("-" * 80)
print("✓ State vector: [payoff_matrix(4), round_number(1)]")
print("✓ Hidden state from previous timestep")
print()
print("✗ NO reward as input")
print("✗ NO opponent action as input")
print("✗ NO action history")
print()

print("FACT 2: Hidden State Update (Deterministic)")
print("-" * 80)
print("h_t, c_t = LSTM(state_t, h_{t-1}, c_{t-1}; weights)")
print()
print("This is PURELY DETERMINISTIC:")
print("  - Same state_t → Same output")
print("  - Same h_{t-1} → Same output")
print("  - Weights are FROZEN (no learning at test time)")
print()
print("→ Hidden state does NOT adapt based on rewards!")
print()

print("FACT 3: Policy Output (Deterministic)")
print("-" * 80)
print("policy_logits = PolicyHead(h_t)")
print("policy_probs = softmax(policy_logits)")
print()
print("For the same hidden state h_t:")
print("  → Same policy probabilities every time")
print()

print("=" * 80)
print("SO WHY DO WE SEE DIFFERENT BEHAVIORS ACROSS OPPONENTS?")
print("=" * 80)
print()

print("HYPOTHESIS 1: Action Sampling Stochasticity")
print("-" * 80)
print("Even with same policy [p_coop=0.6, p_defect=0.4]:")
print("  - Action is SAMPLED randomly from this distribution")
print("  - Different random seeds → Different action sequences")
print("  - But over many games, should average out to p_coop ≈ 0.6")
print()
print("→ This explains variance WITHIN condition, not ACROSS conditions")
print()

print("HYPOTHESIS 2: We're Measuring Outcomes, Not Policies")
print("-" * 80)
print("In the analysis, we calculate cooperation probability FROM REWARDS:")
print()
print("  p_coop = (observed_reward - B) / (A - B)")
print()
print("where:")
print("  A = expected reward when cooperating")
print("  B = expected reward when defecting")
print()
print("But wait - this assumes we KNOW the agent's policy!")
print("If we don't know whether agent cooperated or defected,")
print("we can't directly infer cooperation rate from reward.")
print()
print("Actually, checking the code...")
print()

print("HYPOTHESIS 3: We DO Track Actions During Testing")
print("-" * 80)
print("Looking at the actual test data structure...")
print("The evaluation logs should contain:")
print("  - Agent actions taken")
print("  - Rewards received")
print("  - Opponent actions (for ground truth)")
print()
print("So cooperation rate = count(agent_cooperated) / total_games")
print()
print("If the network is deterministic and inputs are the same,")
print("cooperation rate SHOULD be the same across opponent types!")
print()

print("=" * 80)
print("THE REAL QUESTION")
print("=" * 80)
print()
print("If the network:")
print("  ✓ Receives identical inputs (same game)")
print("  ✓ Has frozen weights (no learning)")
print("  ✓ Updates hidden state deterministically")
print()
print("Then cooperation probability SHOULD be similar across opponents")
print("(within same game, just different opponent p values)")
print()
print("IF we observe large differences, it could mean:")
print()
print("A) There IS some input we're missing (opponent-specific info)")
print("B) Hidden state is NOT reset between test conditions")  
print("C) The network learned opponent-specific policies during TRAINING")
print("   that it can distinguish at test time somehow")
print("D) Our measurement/analysis has a bug")
print()

print("Let's investigate what the data actually shows...")
print()
